######################################################################
# Automatically generated by qmake (3.0) ?? 2? 9 16:09:39 2017
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp
QT += widgets
